title:
headline:
description: Turtle's at the Bottom - Andrew August's Notebook
show_downloads: true
google_analytics: true
theme: jekyll-theme-slate
big_title: Turtles at the Bottom ğŸ¢
little_title: Andrew August's Notebook
plugins:
  - jekyll-sitemap